### ISSUE TITLE
Possible edit for ERRATA Page 39 for webpack config setting `build/sytles.css`

### ISSUE THREAD

**Issue by alexb7217** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#40]
ISSUE:
ERRATA states:
Page 39, alps_trips.library.yml content should be:
```
main:
  version: VERSION
  js:
    build/main.js: {}
  css:
    theme:
      build/style.css: {}
```
---
PROPOSED EDIT:
Should it actually be this?:
```
main:
  version: VERSION
  js:
    build/main.js: {}
  css:
    theme:
      build/styles.css: {}
```
Plural `styles.css` consistent with the config in `webpack.config.js`.
