### ISSUE TITLE
browser don't load the generated asset in themes/custom/alps_trips/build

### ISSUE THREAD

**Issue by YuhaoT** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#70]
In Ch5 - including templates, after include the component from the storybooks and run `ddev theme build`. There is a new folder build with generated asset (.css & .js) by webpack. However, the browser doesn't load those asset and the /forecast/{city} page remain unformat

**Comment by YuhaoT** [comment]
NVM, I missed some config in `alps_trips.info.yml` and `alps_trips.libraris.yml`
in `alps_trips.info.yml`:
```yaml
libraries:
  - alps_trips/main
  ...
```

in `alps_trips.libraris.yml`:
```yaml
main:
  version: VERSION
  js:
    build/main.js: {}
  css:
    theme:
      build/main.css: {}
```
